### ISSUE TITLE
Updating to the latest material-beta.10 breaks the this library.

### ISSUE THREAD

**Issue by tosehee75** [material-extended/mde#10]
```WARNING in ./node_modules/@material-extended/mde/mde.es5.js
4864:17-23 "export 'ESCAPE' was not found in '@angular/cdk'
    at HarmonyImportSpecifierDependency._getErrors (/Users/slee/work/deposco/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/Users/slee/work/deposco/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/slee/work/deposco/node_modules/webpack/lib/Compilation.js:677:24)
    at Compilation.finish (/Users/slee/work/deposco/node_modules/webpack/lib/Compilation.js:535:9)
    at applyPluginsParallel.err (/Users/slee/work/deposco/node_modules/webpack/lib/Compiler.js:512:17)
    at /Users/slee/work/deposco/node_modules/tapable/lib/Tapable.js:289:11
    at /Users/slee/work/deposco/node_modules/html-webpack-plugin/index.js:60:9
    at tryCatcher (/Users/slee/work/deposco/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/slee/work/deposco/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/slee/work/deposco/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/slee/work/deposco/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/slee/work/deposco/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/slee/work/deposco/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/slee/work/deposco/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/slee/work/deposco/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)

WARNING in ./node_modules/@material-extended/mde/mde.es5.js
5257:31-45 "export 'TemplatePortal' was not found in '@angular/cdk'
    at HarmonyImportSpecifierDependency._getErrors (/Users/slee/work/deposco/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/Users/slee/work/deposco/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/slee/work/deposco/node_modules/webpack/lib/Compilation.js:677:24)
    at Compilation.finish (/Users/slee/work/deposco/node_modules/webpack/lib/Compilation.js:535:9)
    at applyPluginsParallel.err (/Users/slee/work/deposco/node_modules/webpack/lib/Compiler.js:512:17)
    at /Users/slee/work/deposco/node_modules/tapable/lib/Tapable.js:289:11
    at /Users/slee/work/deposco/node_modules/html-webpack-plugin/index.js:60:9
    at tryCatcher (/Users/slee/work/deposco/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/slee/work/deposco/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/slee/work/deposco/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/slee/work/deposco/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/slee/work/deposco/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/slee/work/deposco/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/slee/work/deposco/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/slee/work/deposco/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)

WARNING in ./node_modules/@material-extended/mde/mde.es5.js
5361:13-44 "export 'isFakeMousedownFromScreenReader' was not found in '@angular/cdk'
    at HarmonyImportSpecifierDependency._getErrors (/Users/slee/work/deposco/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/Users/slee/work/deposco/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/slee/work/deposco/node_modules/webpack/lib/Compilation.js:677:24)
    at Compilation.finish (/Users/slee/work/deposco/node_modules/webpack/lib/Compilation.js:535:9)
    at applyPluginsParallel.err (/Users/slee/work/deposco/node_modules/webpack/lib/Compiler.js:512:17)
    at /Users/slee/work/deposco/node_modules/tapable/lib/Tapable.js:289:11
    at /Users/slee/work/deposco/node_modules/html-webpack-plugin/index.js:60:9
    at tryCatcher (/Users/slee/work/deposco/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/slee/work/deposco/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/slee/work/deposco/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/slee/work/deposco/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/slee/work/deposco/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/slee/work/deposco/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/slee/work/deposco/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/slee/work/deposco/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)

WARNING in ./node_modules/@material-extended/mde/mde.es5.js
5440:24-34 "export 'A11yModule' was not found in '@angular/cdk'
    at HarmonyImportSpecifierDependency._getErrors (/Users/slee/work/deposco/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/Users/slee/work/deposco/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/slee/work/deposco/node_modules/webpack/lib/Compilation.js:677:24)
    at Compilation.finish (/Users/slee/work/deposco/node_modules/webpack/lib/Compilation.js:535:9)
    at applyPluginsParallel.err (/Users/slee/work/deposco/node_modules/webpack/lib/Compiler.js:512:17)
    at /Users/slee/work/deposco/node_modules/tapable/lib/Tapable.js:289:11
    at /Users/slee/work/deposco/node_modules/html-webpack-plugin/index.js:60:9
    at tryCatcher (/Users/slee/work/deposco/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/slee/work/deposco/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/slee/work/deposco/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/slee/work/deposco/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/slee/work/deposco/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/slee/work/deposco/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/slee/work/deposco/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/slee/work/deposco/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
```

**Comment by tosehee75** [comment]
Reverted the material to beta.8 makes it work. I believe there is some breaking changes introduced in .10.

**Comment by joejordanbrown** [comment]
@tosehee75 

Thanks for reporting the issue.

This shouldn't be a problem with the latest version `^1.0.0`, It's currently version `1.0.0-alpha.3`, have you installed the latest version? Make sure to try `npm install --save @angular/cdk@2.0.0-beta.10 @material-extended/mde@1.0.0-alpha.3` and let me know if the problem persists. 

I bumped the version number because of the breaking changes. It now doesn't depend on `@angular/material` but depends on the new `@angular/cdk`.

I have a StackBlitz example setup https://stackblitz.com/edit/mde-popover which uses the latest `@angualr/cdk`.

**Comment by tosehee75** [comment]
You are right. I was using the 0.1.x version.

I updated and it seems to work.

THanks.

Se Hee Lee

SVP of Technology
------------------------------

4800 N Point Pkwy, Suite 100 | Alpharetta, GA 30022
470-214-3636 | slee@deposco.com | www.deposco.com
<https://deposco.com/?utm_source=Email%20Signature>
Schedule a Conversation <http://staff.deposco.com/>

[image: Twitter]  <https://twitter.com/deposco> [image: Facebook]
<https://facebook.com/deposco> [image: Google +]
<https://plus.google.com/+Deposco> [image: LinkedIn]
<https://www.linkedin.com/company-beta/384437/>

<https://deposco.com/?utm_source=Email%20Signature>
